Shift planning
rakenduste-programmeerimine-2022/workwhen pull request #97
Opened 2022-12-14 12:23 UTC by RValdre

Hopefully nothing explodes

2022-12-14 20:04 UTC, klillenb commented on front/src/components/ShiftPlanningDialog.js
> +            axios.post("http://localhost:8080/todo/add", {
fix link and test

2022-12-14 20:05 UTC, klillenb commented on front/src/components/ShiftPlanningDialog.js
> +                    getData()
no getData fnc defined

2022-12-14 20:07 UTC, klillenb requested changes
ShiftPlanningDialog - fix post link and getData fnc

2022-12-15 21:37 UTC, klillenb reviewed
pray...

2022-12-15 21:37 UTC, klillenb approved these changes
pray again

2022-12-15 21:38 UTC, artjomfrost approved these changes

2022-12-15 21:38 UTC, merged